
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-springboot-examples using AI Type Open AI and AI Model gpt-5

ROOST_METHOD_HASH=sendInlineResourceMail_55f1e810b5
ROOST_METHOD_SIG_HASH=sendInlineResourceMail_2ceab3d7ef

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/unit-java-springboot-examples/1bc77ea8-fc8d-4265-bb55-19e91af08e46/source/spring-boot-examples/spring-boot-mail/src/test/java/com/neo/service/MailServiceTest.java
Tests:
    "@Test
public void sendInlineResourceMail() {
    String rscId = "neo006";
    String content = "<html><body>这是有图片的邮件：<img src=\'cid:" + rscId + "\' ></body></html>";
    String imgPath = "C:\\Users\\ityou\\Pictures\\logo\\smilef.png";
    mailService.sendInlineResourceMail("ityouknow@126.com", "主题：这是有图片的邮件", content, imgPath, rscId);
}
"Scenario 1: Successful send with a valid recipient, subject, HTML content, existing resource path, and valid resource ID

Details:
  TestName: sendsInlineResourceMailSuccessfullyWithValidInputs
  Description: Verifies that the method builds an HTML email with an inline resource and sends it successfully when all inputs are valid. Ensures the correct use of the "from" address, HTML flag, inline resource attachment, and that a success log entry is produced.

Execution:
  Arrange: Set up a MailServiceImpl instance with a mock JavaMailSender and a valid "from" address injected. Configure mailSender.createMimeMessage() to return a new MimeMessage. Provide a valid "to" address, non-empty subject, well-formed HTML content referencing the cid, an existing file path, and a non-empty rscId.
  Act: Invoke sendInlineResourceMail(to, subject, content, rscPath, rscId).
  Assert: Use assertions to verify that:
    - No exception is thrown.
    - mailSender.createMimeMessage() is invoked exactly once.
    - mailSender.send(message) is invoked exactly once with the same MimeMessage instance created.
    - The MimeMessage contains the expected From and To headers.
    - The message body is set as HTML (Content-Type indicates text/html or multipart/related with HTML part).
    - The inline resource with the given rscId is included in the message structure.
  Validation: Confirms that the normal workflow completes, that the helper builds a multipart/related message with inline content, and that the email is sent. This is critical to validate the primary business function of embedding static resources in HTML emails.

*/

// ********RoostGPT********

package com.neo.service.impl;

import jakarta.mail.Address;
import jakarta.mail.BodyPart;
import jakarta.mail.Message;
import jakarta.mail.MessagingException;
import jakarta.mail.Multipart;
import jakarta.mail.Session;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeBodyPart;
import jakarta.mail.internet.MimeMessage;
import jakarta.mail.internet.MimeMultipart;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.core.io.FileSystemResource;
import org.springframework.test.util.ReflectionTestUtils;
import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.Objects;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import org.junit.jupiter.api.*;
import com.neo.service.MailService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Component;

@ExtendWith(MockitoExtension.class)
public class MailServiceImplSendInlineResourceMailTest {

	@Mock
	private org.springframework.mail.javamail.JavaMailSender mailSender;

	@InjectMocks
	private MailServiceImpl mailServiceImpl;

	private String fromAddress;

	@BeforeEach
	public void init() {
		fromAddress = "sender@example.com"; // TODO change to a valid configured sender if
											// needed
		ReflectionTestUtils.setField(mailServiceImpl, "from", (Object) fromAddress);
	}

	@Test
	@Tag("integration")
	public void testSendsInlineResourceMailSuccessfullyWithValidInputs() throws Exception {
		final MimeMessage createdMessage = new MimeMessage((Session) null);
		when(mailSender.createMimeMessage()).thenReturn(createdMessage);
		final File tempFile = Files.createTempFile("inline-res-", ".png").toFile();
		try {
			Files.write(tempFile.toPath(), "data".getBytes(StandardCharsets.UTF_8));
			final String to = "recipient@example.com";
			final String subject = "Subject Line";
			final String rscId = "logo123";
			final String rscPath = tempFile.getAbsolutePath();
			final String content = "<html><body><h1>Hello</h1><img src='cid:" + rscId + "'/></body></html>";
			assertDoesNotThrow(() -> mailServiceImpl.sendInlineResourceMail(to, subject, content, rscPath, rscId));
			verify(mailSender, times(1)).createMimeMessage();
			verify(mailSender, times(1)).send((MimeMessage) createdMessage);
			Address[] froms = createdMessage.getFrom();
			assertNotNull(froms);
			assertTrue(froms.length > 0);
			InternetAddress from0 = (InternetAddress) froms[0];
			assertEquals((String) fromAddress, (String) from0.getAddress());
			Address[] tos = createdMessage.getRecipients(Message.RecipientType.TO);
			assertNotNull(tos);
			assertTrue(tos.length > 0);
			InternetAddress to0 = (InternetAddress) tos[0];
			assertEquals((String) to, (String) to0.getAddress());
			createdMessage.saveChanges();
			Object rawContent = createdMessage.getContent();
			assertNotNull(rawContent);
			assertTrue((rawContent instanceof Multipart));
			Multipart top = (Multipart) rawContent;
			BodyPart htmlPart = findHtmlPartRecursively(top);
			assertNotNull(htmlPart);
			String contentType = (String) htmlPart.getContentType();
			assertTrue((contentType.toLowerCase().contains("text/html")));
			BodyPart inlinePart = findInlineByCidRecursively(top, rscId);
			assertNotNull(inlinePart);
			String[] cidHeaders = inlinePart.getHeader("Content-ID");
			assertNotNull(cidHeaders);
			assertTrue(cidHeaders.length > 0);
			String cidHeader = cidHeaders[0];
			assertTrue((cidHeader.equals("<" + rscId + ">")) || (cidHeader.equals(rscId)));
		}
		finally {
			if (tempFile.exists()) {
				tempFile.delete();
			}
		}
	}

	@Test
	@Tag("invalid")
	public void testSendsInlineResourceMailWithMissingResourcePath() throws Exception {
		final MimeMessage createdMessage = new MimeMessage((Session) null);
		when(mailSender.createMimeMessage()).thenReturn(createdMessage);
		final String to = "recipient@example.com";
		final String subject = "No Resource Available";
		final String rscId = "missingCid";
		final String rscPath = new File("nonexistent-file-path-12345").getAbsolutePath(); // TODO
																							// ensure
																							// path
																							// points
																							// to
																							// a
																							// file
																							// that
																							// does
																							// not
																							// exist
		final String content = "<html><body><p>Content without real resource</p><img src='cid:" + rscId
				+ "'/></body></html>";
		assertDoesNotThrow(() -> mailServiceImpl.sendInlineResourceMail(to, subject, content, rscPath, rscId));
		verify(mailSender, times(1)).createMimeMessage();
		verify(mailSender, times(1)).send((MimeMessage) createdMessage);
		Address[] froms = createdMessage.getFrom();
		assertNotNull(froms);
		InternetAddress from0 = (InternetAddress) froms[0];
		assertEquals((String) fromAddress, (String) from0.getAddress());
		Address[] tos = createdMessage.getRecipients(Message.RecipientType.TO);
		assertNotNull(tos);
		InternetAddress to0 = (InternetAddress) tos[0];
		assertEquals((String) to, (String) to0.getAddress());
	}

	@Test
	@Tag("boundary")
	public void testSendsInlineResourceMailWithEmptySubjectAndMinimalHtml() throws Exception {
		final MimeMessage createdMessage = new MimeMessage((Session) null);
		when(mailSender.createMimeMessage()).thenReturn(createdMessage);
		final File tempFile = Files.createTempFile("inline-res-", ".jpg").toFile();
		try {
			Files.write(tempFile.toPath(), "x".getBytes(StandardCharsets.UTF_8));
			final String to = "recipient@example.com";
			final String subject = "";
			final String rscId = "img";
			final String rscPath = tempFile.getAbsolutePath();
			final String content = "<img src='cid:" + rscId + "'/>";
			assertDoesNotThrow(() -> mailServiceImpl.sendInlineResourceMail(to, subject, content, rscPath, rscId));
			verify(mailSender, times(1)).createMimeMessage();
			verify(mailSender, times(1)).send((MimeMessage) createdMessage);
			Address[] froms = createdMessage.getFrom();
			assertNotNull(froms);
			InternetAddress from0 = (InternetAddress) froms[0];
			assertEquals((String) fromAddress, (String) from0.getAddress());
			Address[] tos = createdMessage.getRecipients(Message.RecipientType.TO);
			assertNotNull(tos);
			InternetAddress to0 = (InternetAddress) tos[0];
			assertEquals((String) to, (String) to0.getAddress());
		}
		finally {
			if (tempFile.exists()) {
				tempFile.delete();
			}
		}
	}

	@Test
	@Tag("invalid")
	public void testDoesNotSendWhenMimeMessageSetContentThrowsMessagingException() throws Exception {
		final MimeMessage throwingMessage = new ThrowingMimeMessage();
		when(mailSender.createMimeMessage()).thenReturn(throwingMessage);
		final String to = "recipient@example.com";
		final String subject = "Will Fail";
		final String rscId = "cid";
		final String content = "<html><body><img src='cid:" + rscId + "'/></body></html>";
		final FileSystemResource dummyRes = new FileSystemResource(new File("no-file")); // will
																							// not
																							// be
																							// read
																							// due
																							// to
																							// early
																							// exception
		assertDoesNotThrow(
				() -> mailServiceImpl.sendInlineResourceMail(to, subject, content, dummyRes.getPath(), rscId));
		verify(mailSender, times(1)).createMimeMessage();
		ArgumentCaptor<MimeMessage> captor = ArgumentCaptor.forClass(MimeMessage.class);
		// Ensure send is never called since preparing message failed with
		// MessagingException
		verify(mailSender, times(0)).send(captor.capture());
	}

	// Utility methods
	private static BodyPart findHtmlPartRecursively(Multipart mp) throws Exception {
		for (int i = 0; i < mp.getCount(); i++) {
			BodyPart part = mp.getBodyPart(i);
			String ct = part.getContentType();
			if (ct != null && ct.toLowerCase().contains("text/html")) {
				return part;
			}
			Object content = part.getContent();
			if (content instanceof Multipart) {
				BodyPart nested = findHtmlPartRecursively((Multipart) content);
				if (nested != null) {
					return nested;
				}
			}
		}
		return null;
	}

	private static BodyPart findInlineByCidRecursively(Multipart mp, String cid) throws Exception {
		for (int i = 0; i < mp.getCount(); i++) {
			BodyPart part = mp.getBodyPart(i);
			String[] cidHeaders = part.getHeader("Content-ID");
			if (cidHeaders != null && cidHeaders.length > 0) {
				for (String h : cidHeaders) {
					if (Objects.equals(h, "<" + cid + ">") || Objects.equals(h, cid)) {
						return part;
					}
				}
			}
			Object content = part.getContent();
			if (content instanceof Multipart) {
				BodyPart nested = findInlineByCidRecursively((Multipart) content, cid);
				if (nested != null) {
					return nested;
				}
			}
		}
		return null;
	}

	// MimeMessage that throws MessagingException when helper tries to set content, to
	// exercise error path
	static class ThrowingMimeMessage extends MimeMessage {

		ThrowingMimeMessage() {
			super((Session) null);
		}

		@Override
		public void setContent(Multipart mp) throws MessagingException {
			throw new MessagingException("forced content failure");
		}

		@Override
		public void setContent(Object o, String type) throws MessagingException {
			throw new MessagingException("forced content failure");
		}

	}

}