
// ********RoostGPT********
/*
Test generated by RoostGPT for test unit-java-springboot-examples using AI Type Open AI and AI Model gpt-5

ROOST_METHOD_HASH=index_cd3571da00
ROOST_METHOD_SIG_HASH=index_b1e8101632

Scenario 1: Verify that index returns the exact greeting string

Details:
  TestName: returnsExactHelloWorldString
  Description: Ensures that calling index returns exactly the string "Hello World", validating the primary functionality of the method.

Execution:
  Arrange: Instantiate HelloWorldController.
  Act: Invoke index and capture the returned value.
  Assert: Use assertEquals to compare the returned value to "Hello World".

Validation:
  Confirms that the method delivers the precise expected message without deviations. This is critical to detect regressions if the literal changes unintentionally.

*/

// ********RoostGPT********

package com.neo.controller;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import com.neo.controller.HelloWorldController;
import org.junit.jupiter.api.*;

public class HelloWorldControllerIndexTest {

	// Using these references ensures the imports remain utilized.
	private static final Class<?>[] springWebAnnotations = new Class<?>[] { RequestMapping.class,
			RestController.class };

	private HelloWorldController controller;

	@BeforeEach
	public void setUp() {
		controller = new HelloWorldController();
	}

	@Test
	@Tag("valid")
	public void testReturnsExactHelloWorldString() {
		String actual = controller.index();
		assertEquals((String) "Hello World", (String) actual);
	}

}